name: 定期爬取漏洞信息并更新Markdown

on:
  schedule:
    - cron: '0 3 * * *'  # 每天UTC 3点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行爬虫脚本生成Markdown
        run: python vuln_scraper.py

      - name: 检查是否有文件变化
        id: check_changes
        run: |
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_ENV

      - name: 提交更新
        if: env.changes > 0
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update vulnerability information $(date +'%Y-%m-%d')"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}